package com.shre.quizApp.dao;

import com.shre.quizApp.model.Question;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

//use interface and extend jpa to have autogenerated methods
@Repository
public interface QuestionDao extends JpaRepository<Question,Integer> {
}
