package com.shre.quizApp.dao;

import com.shre.quizApp.model.Question;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.List;

//use interface and extend jpa to have autogenerated methods
@Repository
public interface QuestionDao extends JpaRepository<Question,Integer> {
    List<Question> findByCategory(String category); //method to return the column based value
}
